### ISSUE TITLE
Problém s testovaním

### ISSUE THREAD

**Issue by TimurKr** [gjenca/test_mboxer#1]
Pri zbehnutí testov píše výstupovú chybu pri každom teste okrem prvého: 
```
Traceback (most recent call last):
  File "/ceste/ku/repozitáru/mboxer/test_mboxer-main/test<číslo testu>/../mboxer.py", line 281, in <module>
    s.bind(('', 9999))
OSError: [Errno 48] Address already in use
```
Aj po ukončení všetkých testov ak sa pokúsim rozbehnúť server pre osobné testovanie, píše mi, že adresa je používaná. Domnievam sa, že pri testovaní zlyháva killall. Môže ísť o chybu z dôsledku operačného systému, keďže pracujem na macos.

Našiel som však riešenie, ktoré by malo fungovať aj na macos aj linux. Nájsť PID procesu pripojeného na porte 9999 príkazom
```
lsof -t -i :9999 | xargs kill
```
Tento príkaz ukončí všetky procesy pripojené na port 9999.

Bez takejto úpravy nie som schopný otestovať môj kód, nakoľko nový server sa nerozbehne pri novom teste a teda ten pôvodný nemá prístup k potrebným priečinkom a správam.

**Comment by gjenca** [comment]
Vdaka, pozriem sa na to.

--
GJ


Dňa st 22. 3. 2023 o 23:37 Timur Kramár ***@***.***>
napísala(a):

**Comment by gjenca** [comment]
Konečne som sa k tomu dostal. Reprodukovať Váš problém neviem, ale skúste novú verziu, prerobil som to tak, aby sa explicitne ukončoval ten PID, ktorý sa spustil.

**Comment by TimurKr** [comment]
Bohužial mi to nefungovalo, domnievam sa však, že to bude iba z dôvodu iného OS. Podarilo sa mi však upraviť tie vaše testy tak aby mi to išlo. Ak to vám ide na Linuxe, tak potom to pôjde asi aj všetkým ostatným študentom. Každopádne mám ešte otázku ohladom testu č.9.

Test pozostáva z 3 častí, `WRITE`, `LS` a `READ`. Pri druhej, teda `LS` požiadavke, Je očakávaná odpoveď iba jedna, avšak priečinok `xxx` obsahuje naozaj až 2 správy. Nachádza sa tam aj priečinok `xxx.good`, ktorý obsahuje iba jeden súbor, ktorý má aj rovnaký názov ako je očakávaná správna odpoveď, ale server prirodzene číta z mailboxu xxx, teda podľa mna je odpoveď s dvoma správami správna.

**Comment by TimurKr** [comment]
Tu je link na môj [repozitár](https://github.com/TimurKr/mboxer.git), kde je posladná verzia môjho kódu. Pri mojom testovaní prešli všetky testy okrem č.9. Možno sa vám chybu podarí reprodukovať s mojim kódom.
